### ISSUE TITLE
Turning "Silicon Spacer" model into "Metal Cap" model

### ISSUE THREAD

**Issue by juliencarponcy** [cortex-lab/neuropixels#34]
Hi,

We have acquired 3b versions with silicon spacer instead of metal cap which was not available at time of purchase. Do you know if the following fit that purpose : https://hhmi.flintbox.com/#technologies/134cfd77-6fde-4bdd-ae1f-4c7900e45f77

Or would you have an alternative solution like stl files for metal cap, how to fix them on a silicon spacer etc etc. 

The aim is to have them easily fitted into already existing custom-design holder.

Thank you very much for your help,

Julien

**Comment by grahamfindlay** [comment]
Hi Julien,

Yes, you can have the dovetail caps that you linked to machined, and then attach them to your cap-less probes. There should be a PDF in there with an explanation and visual walkthrough of the mounting procedures. If, like me, you do not have easy access to machinists skilled enough to do this very fine & precise work, you can also purchase caps directly from Sensapex ([here](https://shop.sensapex.com/product/ump-np-cap/)). The hole in the center of the Sensapex caps is a nice feature, because it makes it easy to place the cap on the spacer and align it to the shank, then fill the hole with cyanoacrylate once your are satisfied that the alignment is good. Because you do not need to have the alignment perfect on first contact with the spacer, I have found that I can do without the profile projector suggested in the Janelia docs. 

Good luck,
Graham

**Comment by juliencarponcy** [comment]
Thank you very muh Graham,

All your comments plus others input have been very helpful. I ordered the items fron Sensapex.

Best wishes,

Julien
